restoring error checking to modified files determination step

diff --git a/.github/workflows/pre-commit-check-and-autocommit-changes.yaml b/.github/workflows/pre-commit-check-and-autocommit-changes.yaml
--- a/.github/workflows/pre-commit-check-and-autocommit-changes.yaml
+++ b/.github/workflows/pre-commit-check-and-autocommit-changes.yaml
@@ -58,7 +58,13 @@ jobs:
           HEAD_REF: ${{ github.head_ref }}
         run: |
             MODIFIED_FILES=$(git diff --name-only origin/${BASE_REF} origin/${HEAD_REF})
-            echo '::set-output name=modified_files::$MODIFIED_FILES'
+            if [ -z "$MODIFIED_FILES" ]; then
+                echo "No changed files detected on this branch? This must be an error."
+                exit 1
+            else
+                echo "Running checks on the following files: ${MODIFIED_FILES}"
+                echo '::set-output name=modified_files::$MODIFIED_FILES'
+            fi
 
       # Install terraform-docs for pre-commit hook
       - name: Install terraform-docs
